# Configuration for electrophysiology feature computation and region inference
pid: "afe87fbb-3a17-461f-b333-e22903f1d70d"  # Probe ID
t_start: 300.0  # Start time in seconds
duration: 1  # Duration in seconds

#Big .cbin files
# ap_file: "/Users/pranavrai/Downloads/ONE/alyx.internationalbrainlab.org/angelakilab/Subjects/NYU-48/2021-06-28/001/raw_ephys_data/probe00/_spikeglx_ephysData_g0_t0.imec0.ap.cbin"
# lf_file: "/Users/pranavrai/Downloads/ONE/alyx.internationalbrainlab.org/angelakilab/Subjects/NYU-48/2021-06-28/001/raw_ephys_data/probe00/_spikeglx_ephysData_g0_t0.imec0.lf.cbin"

#Small .cbin files
# lf_file: "/Users/pranavrai/Downloads/ONE/alyx.internationalbrainlab.org/cache/lf/mainenlab/Subjects/ZM_1898/2019-12-10/007/raw_ephys_data/probe00/chunk_001799_to_001800/_spikeglx_ephysData_g1_t0.imec.lf.stream.cbin"
# ap_file: "/Users/pranavrai/Downloads/ONE/alyx.internationalbrainlab.org/cache/ap/mainenlab/Subjects/ZM_1898/2019-12-10/007/raw_ephys_data/probe00/chunk_001799_to_001800/_spikeglx_ephysData_g1_t0.imec.ap.stream.cbin"
# Trajectory information for xyz target computation
# traj_dict:
#   x: -2243.1  # x coordinate
#   y: -1999.8  # y coordinate
#   z: -361.0  # z coordinate
#   depth: 4000.0  # insertion depth
#   theta: 15.0  # insertion angle theta
#   phi: 180.0  # insertion angle phi



# Operation mode: 'features' for feature computation only,
# 'inference' for region inference only, or 'both' for both operations
mode: "features"

# Path to output directory.
output_dir: "/Users/pranavrai/Work/int-brain-lab/temp/features"
# Path to the model directory for region inference
model_path: "/Users/pranavrai/Downloads/models/2024_W50_Cosmos_voter-snap-pudding/"  # Path to the model directory

#python main.py --config config.yaml