[project]
name = "ibl_python_template"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "International Brain Laboratory", email = "software-devs@internationalbrainlab.org"},
]
dependencies = [
    "one-api>=2.0.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "spikeglx>=0.1.0",
    "ibl-neuropixel>=1.0.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true


[dependency-groups]
lint = ["ruff>=0.7.3"]

#Add dev dependencies for testing.
