[project]
name = "ibleatools"
version = "0.1.0"
description = "Tools for IBL data analysis and processing"
authors = [
    {name = "International Brain Laboratory", email = "software-devs@internationalbrainlab.org"},
]
dependencies = [
    "dartsort @ git+https://github.com/cwindolf/dartsort@iblsorter",
    "dredge @ git+https://github.com/evarol/dredge@v0.2.2",
    "h5py",
    "hdbscan",
    "iblatlas>=0.3.0",
    "ibllib",
    "linear-operator",
    "matplotlib",
    "mock",
    "numba",
    "numpy>=2.0",
    "opt-einsum",
    "pandas",
    "pandera",
    "pydantic",
    "pytest",
    "scikit-learn",
    "scipy>=1.13",
    "seaborn",
    "spikeinterface",
    "torch>=2.0",
    "tqdm",
    "xgboost",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Neuroscience :: Data analysis",
    "Programming Language :: Python :: 3.10",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.package-dir]
ibleatools = "src/ibleatools"

[tool.pdm.packages]
include = ["src/ibleatools"]

[[tool.pdm.source]]
name = "23b9ae"
url = "https://download.pytorch.org/whl/cpu"
verify_ssl = true
[dependency-groups]
lint = ["ruff>=0.7.3"]

#Add dev dependencies for testing.
