name: Build and Test

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        name: ruff check
        with:
          args: 'check --output-format=github'
      - uses: chartboost/ruff-action@v1
        name: ruff format
        with:
          args: 'format --check'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install --group test

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s tests -v
        coverage xml
        coverage report
    
    - name: Coveralls
      uses: coverallsapp/github-action@v2