name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        name: ruff check
        with:
          args: 'check --output-format=github'
      - uses: chartboost/ruff-action@v1
        name: ruff format
        with:
          args: 'format --check'

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        pdm install -dG test

    - name: Run tests with coverage
      run: |
        pdm run coverage run -m unittest discover -s tests -v
        pdm run coverage xml
        pdm run coverage report
    
    - name: Coveralls
      uses: coverallsapp/github-action@v2